global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:

scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['gosh-nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['gosh-cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['gosh-pushgateway:9091']

  - job_name: 'trcnt-stat'
    scrape_interval: 15s
    static_configs:
      - targets: ['trcnt-stat:9123']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'gosh-alertmanager:9093'


