port:    9123
prefix:  trcnt_stat_

timeout:     10000
libtimeout:  10000

networks:
  gosh: "network.gosh.sh"
# test: "vps23.ton.dev"

values:
  - 31000
  - 15
  - 20
  - 17
  - 16
  - 2
  - 1.4
  - 1.6
  - 6
  - 1.3
  - 18
  - 60
  - ^31000
  - ^60
